[package]
name = "forbidden-donut"
version = "0.1.0"
authors = ["Jarred Barber <jpb5082@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "*"
crossterm = "*"
rand = "*"
